In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
import tensorflow as tf
import keras

In [3]:
len_emb=500 ##any given length of the embedding

emb_1=np.random.randn(1,len_emb)
emb_2=np.random.randn(1,len_emb)
emb_3=np.random.randn(1,len_emb)
emb_4=np.random.randn(1,len_emb)
emb_5=np.random.randn(1,len_emb)

embs_odd=np.array([emb_1,emb_2,emb_3,emb_4,emb_5]) ##subcategory with odd number of nodes

embs_even=np.array([emb_1,emb_2,emb_3,emb_4]) ##subcategory with even number of nodes

In [4]:
##function to aggregate embeddings over a subcategory
##takes an array of all embeddings as input
def agg_sub(embs):
    ##lengths of each node embedding
    m=len(embs[0][0])
    ##intializing the transpose of the first embedding for matrix multiplication
    result=np.transpose(embs[0])
    ##looping over the rest of the embeddings performing matrix multiplication
    for i in range(1,len(embs)):
        if i%2==0:
            result=result.dot(np.transpose(embs[i]))
        elif i%2==1:
            result=result.dot(embs[i])

    ##reducing using activation function
    result=np.tanh(result)
    
    ##implementation of pooling using keras
    ##only in cases when number of nodes is even
    if len(embs)%2==0:
        ##instaniating the pooling layer
        avg_pool_2d=tf.keras.layers.AveragePooling2D(pool_size=(1,m), padding='valid')
        ##keras pooling layers requires vectors to be in 4-dimensions for processing
        result=tf.reshape(result,[1,m,m,1])
        ##applying average pooling to get vector of size (m*1)
        result=avg_pool_2d(result)
        ##converting back to 2-d array
        result=tf.reshape(result,[m,1])
        result=np.array(result)
    else:
        pass
    
    return result

In [5]:
agg_sub(embs_odd)

array([[ 1.        ],
       [ 1.        ],
       [-1.        ],
       [ 0.98357503],
       [-0.98478498],
       [ 1.        ],
       [ 1.        ],
       [ 1.        ],
       [-1.        ],
       [ 1.        ],
       [ 1.        ],
       [ 0.99999321],
       [ 1.        ],
       [ 1.        ],
       [-1.        ],
       [-1.        ],
       [ 1.        ],
       [-1.        ],
       [ 1.        ],
       [ 1.        ],
       [ 1.        ],
       [ 1.        ],
       [ 1.        ],
       [ 1.        ],
       [-1.        ],
       [ 0.99999837],
       [-1.        ],
       [-1.        ],
       [-0.4922297 ],
       [ 1.        ],
       [ 1.        ],
       [-1.        ],
       [ 1.        ],
       [-1.        ],
       [ 1.        ],
       [-1.        ],
       [ 0.99981704],
       [ 1.        ],
       [-0.99999942],
       [-1.        ],
       [-1.        ],
       [ 1.        ],
       [ 0.98751094],
       [-1.        ],
       [ 1.        ],
       [-1

In [6]:
agg_sub(embs_even)

array([[ 0.01292743],
       [ 0.0133335 ],
       [-0.01254517],
       [ 0.00860468],
       [-0.00873737],
       [ 0.01334161],
       [ 0.01308604],
       [ 0.01243432],
       [-0.01346108],
       [ 0.01339432],
       [ 0.0137694 ],
       [ 0.01438202],
       [ 0.01344329],
       [ 0.01337176],
       [-0.01329733],
       [-0.01382851],
       [ 0.01185543],
       [-0.01338267],
       [ 0.01334087],
       [ 0.01336316],
       [ 0.01291239],
       [ 0.01336839],
       [ 0.01335459],
       [ 0.0133948 ],
       [-0.01362251],
       [ 0.01440978],
       [-0.01199649],
       [-0.0133948 ],
       [-0.00160667],
       [ 0.01276607],
       [ 0.01335192],
       [-0.01250902],
       [ 0.01174252],
       [-0.01304108],
       [ 0.01302401],
       [-0.01336618],
       [ 0.01351759],
       [ 0.01336923],
       [-0.01436322],
       [-0.01337197],
       [-0.01336277],
       [ 0.01304257],
       [ 0.00907192],
       [-0.01270186],
       [ 0.01333021],
       [-0

In [7]:
len_sub=500 ##any given length of the embedding

sub_1=np.random.randn(len_emb,1)
sub_2=np.random.randn(len_emb,1)
sub_3=np.random.randn(len_emb,1)
sub_4=np.random.randn(len_emb,1)
sub_5=np.random.randn(len_emb,1)

subs_odd=np.array([sub_1,sub_2,sub_3,sub_4,sub_5]) ##subcategory with odd number of nodes

subs_even=np.array([sub_1,sub_2,sub_3,sub_4]) ##subcategory with even number of nodes

In [8]:
##function to aggregate subcategory embeddings over a category
##takes an array of all embeddings as input
def agg_cat(subs):
    ##lengths of each node embedding
    m=subs[0].shape[0]
    ##intializing the transpose of the first embedding for matrix multiplication
    result=subs[0]
    ##looping over the rest of the embeddings performing matrix multiplication
    for i in range(1,len(subs)):
        if i%2==0:
            result=result.dot(subs[i])
        elif i%2==1:
            result=result.dot(np.transpose(subs[i]))
    
    print(result)
    ##apply activation function on the array
    result=np.tanh(result)
    
    
    ##implementation of pooling using keras
    ##only in cases when number of nodes is even
    if len(subs)%2==0:
        ##instaniating the pooling layer
        avg_pool_2d=tf.keras.layers.AveragePooling2D(pool_size=(1,m), padding='valid')
        ##keras pooling layers requires vectors to be in 4-dimensions for processing
        result=tf.reshape(result,[1,m,m,1])
        ##applying average pooling to get vector of size (m*1)
        result=avg_pool_2d(result)
        ##converting back to 2-d array
        result=tf.reshape(result,[m,1])
        result=np.array(result)
    else:
        pass
    
    return result

In [9]:
agg_cat(subs_odd)

[[-2.43921480e+01]
 [-2.69872894e+02]
 [ 2.19840840e+02]
 [-6.34612966e+01]
 [ 2.31880531e+01]
 [-6.40776134e+00]
 [ 1.02004108e+02]
 [ 1.49397416e+02]
 [ 1.78063479e+02]
 [-1.60296480e+00]
 [-1.05615966e+02]
 [ 5.89105376e+01]
 [ 2.93393767e+02]
 [-9.31077485e+01]
 [-2.26921084e+02]
 [-1.13019829e+01]
 [ 1.61150492e+01]
 [-9.91910201e+00]
 [-1.99189798e+02]
 [-1.33362892e+01]
 [ 3.54190688e+02]
 [-4.04823568e+01]
 [-8.39012990e+01]
 [-2.29145539e-01]
 [-1.29551098e+01]
 [ 1.32341615e+01]
 [-1.04323972e+02]
 [-4.72193723e+01]
 [-1.97442148e+02]
 [ 5.63043652e+01]
 [-1.68869354e+02]
 [ 1.31154372e+02]
 [ 3.12555490e+02]
 [ 8.48720315e+01]
 [-3.22582131e+01]
 [ 1.50217443e+02]
 [ 1.08963337e+02]
 [-9.10562480e+01]
 [ 7.12808490e+01]
 [-6.35652788e+01]
 [ 4.44277522e+02]
 [-7.51373237e+00]
 [-1.61474521e+02]
 [-7.47994159e+01]
 [-1.80145167e+02]
 [ 2.60455114e+02]
 [-2.54075626e+01]
 [ 1.93111550e+02]
 [-1.95205209e+00]
 [-1.63399341e+02]
 [-2.49057057e+01]
 [ 6.97607705e+00]
 [ 6.1097492

array([[-1.        ],
       [-1.        ],
       [ 1.        ],
       [-1.        ],
       [ 1.        ],
       [-0.99999456],
       [ 1.        ],
       [ 1.        ],
       [ 1.        ],
       [-0.92211362],
       [-1.        ],
       [ 1.        ],
       [ 1.        ],
       [-1.        ],
       [-1.        ],
       [-1.        ],
       [ 1.        ],
       [-1.        ],
       [-1.        ],
       [-1.        ],
       [ 1.        ],
       [-1.        ],
       [-1.        ],
       [-0.22521739],
       [-1.        ],
       [ 1.        ],
       [-1.        ],
       [-1.        ],
       [-1.        ],
       [ 1.        ],
       [-1.        ],
       [ 1.        ],
       [ 1.        ],
       [ 1.        ],
       [-1.        ],
       [ 1.        ],
       [ 1.        ],
       [-1.        ],
       [ 1.        ],
       [-1.        ],
       [ 1.        ],
       [-0.9999994 ],
       [-1.        ],
       [-1.        ],
       [-1.        ],
       [ 1

In [10]:
agg_cat(subs_even)

[[ -0.99314961  -1.74808044  -1.24601602 ...  -0.04060281  -0.72984189
   -0.85594496]
 [-10.98813271 -19.34063082 -13.78582768 ...  -0.44922646  -8.07491595
   -9.47011076]
 [  8.95102984  15.75504848  11.23005684 ...   0.36594383   6.57789777
    7.71443576]
 ...
 [ -8.66271554 -15.24757551 -10.86833468 ...  -0.35415672  -6.36602249
   -7.46595239]
 [ -2.24245122  -3.94702378  -2.81340305 ...  -0.09167785  -1.64792377
   -1.93265425]
 [ -0.8790518   -1.54725255  -1.1028677  ...  -0.03593816  -0.64599415
   -0.75760988]]


array([[ 1.00553036e-02],
       [-2.01290548e-02],
       [ 1.92541424e-02],
       [-3.89752397e-03],
       [-1.06140850e-02],
       [ 1.03771007e-02],
       [ 1.11779245e-02],
       [ 1.61426701e-02],
       [ 1.78209785e-02],
       [ 3.06128082e-03],
       [-1.16848275e-02],
       [ 2.74046464e-03],
       [ 2.03764290e-02],
       [-9.81827825e-03],
       [-1.94191113e-02],
       [ 1.34808728e-02],
       [-1.33142434e-02],
       [ 1.30204940e-02],
       [-1.86593402e-02],
       [ 1.36919459e-02],
       [ 2.07850449e-02],
       [ 3.05148447e-03],
       [-8.22987035e-03],
       [ 4.42756776e-04],
       [ 1.36891110e-02],
       [-1.36926835e-02],
       [-1.15063796e-02],
       [ 6.88913569e-04],
       [-1.85998809e-02],
       [ 2.03746674e-03],
       [-1.73612218e-02],
       [ 1.46224974e-02],
       [ 2.05329899e-02],
       [ 8.40671267e-03],
       [ 6.41786819e-03],
       [ 1.62016470e-02],
       [ 1.21327350e-02],
       [-9.48104169e-03],
       [ 5.7